In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [33]:
import numpy as np
a = np.array([[1,1,1],[1,2,2],[1,3,3],[3,4,4]])
uv = np.unique(a[:,1])[1:]
print(uv)
#uv = np.unique(a[:,1])[1:]
#print(uv)

[2 3 4]


In [37]:
import numpy as np 
a = np.empty(0)
s = a.size
print(s)

0


In [69]:
import numpy as np
import pandas as pd
from binarizer import StandardBinarizer

def csv_to_Matrix(path):
    x_Matrix = pd.read_csv(path, header=None)
    x_Matrix = np.array(x_Matrix)
    return x_Matrix

x = csv_to_Matrix('IRIS.csv')
#print(x)
binarizer = StandardBinarizer(max_bits_per_feature=10)
binarizer.fit(x)
x = binarizer.transform(x)


x = x.astype(int)
print(x)



[[1 1 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 0 1 1]]
